### ISSUE TITLE
cython extensions

### ISSUE THREAD

**Issue by esquires** [slaypni/fastdtw#3]
This is a great library. Thank you for open sourcing it. It would be nice if it ran a bit faster perhaps with cython extensions. Is there any interest in that?

**Comment by slaypni** [comment]
It would be nice if this library runs faster in that way. I feel this library is not very fast when processing non small data although the complexity is O(N).

I have no plan to continue to develop this library, because I have no need to use DTW at this moment. It would be very nice if someone implement it.

**Comment by slaypni** [comment]
It would be nice if this library runs faster in that way. I feel this library is not fast when processing non small data although the complexity is O(N).

I have no plan to continue to develop this library at this time, because I have no need to use DTW at this moment. It would be very nice if someone implements it!

**Comment by esquires** [comment]
Thanks for the feedback. If I fork it and put in a pull request will you
incorporate it?

Eric

**Comment by slaypni** [comment]
I will!

**Comment by esquires** [comment]
see https://github.com/slaypni/fastdtw/pull/4

**Comment by esquires** [comment]
Given pulls #5 and #6 I think this issue can be closed.

**Comment by slaypni** [comment]
Close this issue since #5 and #6 are merged.
